FROM golang:1.4-cross
ADD . /go/src/github.com/ehazlett/redirector
ADD https://get.docker.com/builds/Linux/x86_64/docker-1.7.0 /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker
WORKDIR /go/src/github.com/ehazlett/redirector

